-- Created on every shard at start.
-- listed_with_key: in [[omnisharded_tables]] (sticky) and has the sharding-key column org_id.
CREATE TABLE listed_with_key (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id integer,
  name text
);
-- unlisted_no_key: not in [[omnisharded_tables]], no sharding-key column.
CREATE TABLE unlisted_no_key (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listed_id integer NOT NULL
);
-- Control pair: neither listed, neither has the sharding key.
CREATE TABLE unlisted_a (id integer PRIMARY KEY, name text);
CREATE TABLE unlisted_b (id integer PRIMARY KEY, a_id integer NOT NULL);
